# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'synergiesGUI.ui'
#
# Created: Fri Oct 14 12:52:03 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SynergiesGUI(object):
    def setupUi(self, SynergiesGUI):
        SynergiesGUI.setObjectName("SynergiesGUI")
        SynergiesGUI.resize(856, 726)
        self.centralwidget = QtGui.QWidget(SynergiesGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 110, 371, 271))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(30, 80, 121, 31))

        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 80, 121, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 140, 121, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 140, 121, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtGui.QLineEdit('Max_',self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 200, 121, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(190, 200, 121, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 10, 371, 31))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 20, 401, 361))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 361, 31))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.frame = QtGui.QFrame(self.groupBox_2)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 131))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.VR_Button = QtGui.QToolButton(self.frame)
        self.VR_Button.setGeometry(QtCore.QRect(50, 50, 71, 61))
        self.VR_Button.setCheckable(True)
        self.VR_Button.setAutoExclusive(True)
        self.VR_Button.setObjectName("VR_Button")
        self.UR5_Button = QtGui.QToolButton(self.frame)
        self.UR5_Button.setGeometry(QtCore.QRect(290, 50, 71, 61))
        self.UR5_Button.setCheckable(True)
        self.UR5_Button.setAutoExclusive(True)
        self.UR5_Button.setObjectName("UR5_Button")
        self.define_Button = QtGui.QToolButton(self.frame)
        self.define_Button.setGeometry(QtCore.QRect(170, 50, 71, 61))
        self.define_Button.setCheckable(True)
        self.define_Button.setAutoExclusive(True)
        self.define_Button.setObjectName("define_Button")
        self.stackedWidget = QtGui.QStackedWidget(self.groupBox_2)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 140, 381, 221))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.VRprevButton = QtGui.QToolButton(self.page)
        self.VRprevButton.setGeometry(QtCore.QRect(50, 100, 81, 41))
        self.VRprevButton.setObjectName("VRprevButton")
        self.VRNextButton = QtGui.QToolButton(self.page)
        self.VRNextButton.setGeometry(QtCore.QRect(240, 100, 81, 41))
        self.VRNextButton.setObjectName("VRNextButton")
        self.VRHomeButton = QtGui.QToolButton(self.page)
        self.VRHomeButton.setGeometry(QtCore.QRect(150, 40, 81, 61))
        self.VRHomeButton.setObjectName("VRHomeButton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.getPosButton = QtGui.QToolButton(self.page_2)
        self.getPosButton.setGeometry(QtCore.QRect(30, 20, 71, 41))
        self.getPosButton.setObjectName("getPosButton")
        self.displayPos = QtGui.QLabel(self.page_2)
        self.displayPos.setGeometry(QtCore.QRect(120, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.displayPos.setFont(font)
        self.displayPos.setObjectName("displayPos")
        self.displayHome = QtGui.QLabel(self.page_2)
        self.displayHome.setGeometry(QtCore.QRect(80, 70, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.displayHome.setFont(font)
        self.displayHome.setAlignment(QtCore.Qt.AlignCenter)
        self.displayHome.setObjectName("displayHome")
        self.genCoorButton = QtGui.QToolButton(self.page_2)
        self.genCoorButton.setGeometry(QtCore.QRect(30, 150, 351, 51))
        self.genCoorButton.setObjectName("genCoorButton")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.URPrevButton = QtGui.QToolButton(self.page_3)
        self.URPrevButton.setGeometry(QtCore.QRect(50, 100, 81, 41))
        self.URPrevButton.setObjectName("URPrevButton")
        self.URNextButton = QtGui.QToolButton(self.page_3)
        self.URNextButton.setGeometry(QtCore.QRect(240, 100, 81, 41))
        self.URNextButton.setObjectName("URNextButton")
        self.URHomeButton = QtGui.QToolButton(self.page_3)
        self.URHomeButton.setGeometry(QtCore.QRect(150, 40, 81, 61))
        self.URHomeButton.setObjectName("URHomeButton")
        self.stackedWidget.addWidget(self.page_3)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(490, 410, 301, 231))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.record_Button = QtGui.QToolButton(self.frame_2)
        self.record_Button.setGeometry(QtCore.QRect(50, 20, 71, 71))
        self.record_Button.setStyleSheet("QToolButton:checked {\n"
"\n"
"background-color: rgb(200, 18, 2);\n"
"\n"
"}")
        self.record_Button.setCheckable(True)
        self.record_Button.setChecked(False)
        self.record_Button.setAutoExclusive(True)
        self.record_Button.setObjectName("record_Button")
        self.stop_Button_4 = QtGui.QToolButton(self.frame_2)
        self.stop_Button_4.setGeometry(QtCore.QRect(170, 20, 71, 71))
        self.stop_Button_4.setCheckable(True)
        self.stop_Button_4.setChecked(True)
        self.stop_Button_4.setAutoExclusive(True)
        self.stop_Button_4.setObjectName("stop_Button_4")
        self.trialNumber = QtGui.QLCDNumber(self.frame_2)
        self.trialNumber.setGeometry(QtCore.QRect(100, 110, 101, 91))
        self.trialNumber.setDigitCount(2)
        self.trialNumber.setObjectName("trialNumber")
        self.connectButton = QtGui.QToolButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(30, 30, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.connectButton.setFont(font)
        self.connectButton.setStyleSheet("QToolButton:checked {\n"
"\n"
"background-color: rgb(0, 170, 0);\n"
"\n"
"}")
        self.connectButton.setCheckable(True)
        self.connectButton.setChecked(False)
        self.connectButton.setObjectName("connectButton")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 410, 371, 251))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        SynergiesGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SynergiesGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        SynergiesGUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SynergiesGUI)
        self.statusbar.setObjectName("statusbar")
        SynergiesGUI.setStatusBar(self.statusbar)
        self.actionLicense = QtGui.QAction(SynergiesGUI)
        self.actionLicense.setObjectName("actionLicense")
        self.actionContact = QtGui.QAction(SynergiesGUI)
        self.actionContact.setObjectName("actionContact")
        self.menuAbout.addAction(self.actionLicense)
        self.menuAbout.addAction(self.actionContact)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(SynergiesGUI)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SynergiesGUI)
        SynergiesGUI.setTabOrder(self.VR_Button, self.UR5_Button)
        SynergiesGUI.setTabOrder(self.UR5_Button, self.define_Button)
        SynergiesGUI.setTabOrder(self.define_Button, self.VRprevButton)
        SynergiesGUI.setTabOrder(self.VRprevButton, self.VRNextButton)
        SynergiesGUI.setTabOrder(self.VRNextButton, self.VRHomeButton)
        SynergiesGUI.setTabOrder(self.VRHomeButton, self.getPosButton)
        SynergiesGUI.setTabOrder(self.getPosButton, self.genCoorButton)
        SynergiesGUI.setTabOrder(self.genCoorButton, self.URPrevButton)
        SynergiesGUI.setTabOrder(self.URPrevButton, self.URNextButton)
        SynergiesGUI.setTabOrder(self.URNextButton, self.URHomeButton)
        SynergiesGUI.setTabOrder(self.URHomeButton, self.record_Button)
        SynergiesGUI.setTabOrder(self.record_Button, self.stop_Button_4)

    def retranslateUi(self, SynergiesGUI):
        SynergiesGUI.setWindowTitle(QtGui.QApplication.translate("SynergiesGUI", "Serial Experiments Synergies", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("SynergiesGUI", "Age", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("SynergiesGUI", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_3.setText(QtGui.QApplication.translate("SynergiesGUI", "Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_6.setText(QtGui.QApplication.translate("SynergiesGUI", "Arm_Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SynergiesGUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Experiment Data Input</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SynergiesGUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Target Controller</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.VR_Button.setText(QtGui.QApplication.translate("SynergiesGUI", "VR Target", None, QtGui.QApplication.UnicodeUTF8))
        self.UR5_Button.setText(QtGui.QApplication.translate("SynergiesGUI", "UR5", None, QtGui.QApplication.UnicodeUTF8))
        self.define_Button.setText(QtGui.QApplication.translate("SynergiesGUI", "Define", None, QtGui.QApplication.UnicodeUTF8))
        self.VRprevButton.setText(QtGui.QApplication.translate("SynergiesGUI", "Prev", None, QtGui.QApplication.UnicodeUTF8))
        self.VRNextButton.setText(QtGui.QApplication.translate("SynergiesGUI", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.VRHomeButton.setText(QtGui.QApplication.translate("SynergiesGUI", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.getPosButton.setText(QtGui.QApplication.translate("SynergiesGUI", "Get Pos", None, QtGui.QApplication.UnicodeUTF8))
        self.displayPos.setText(QtGui.QApplication.translate("SynergiesGUI", "Position Display", None, QtGui.QApplication.UnicodeUTF8))
        self.displayHome.setText(QtGui.QApplication.translate("SynergiesGUI", "HOME POSITION", None, QtGui.QApplication.UnicodeUTF8))
        self.genCoorButton.setText(QtGui.QApplication.translate("SynergiesGUI", "Generate Target Coordinates", None, QtGui.QApplication.UnicodeUTF8))
        self.URPrevButton.setText(QtGui.QApplication.translate("SynergiesGUI", "Prev", None, QtGui.QApplication.UnicodeUTF8))
        self.URNextButton.setText(QtGui.QApplication.translate("SynergiesGUI", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.URHomeButton.setText(QtGui.QApplication.translate("SynergiesGUI", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.record_Button.setText(QtGui.QApplication.translate("SynergiesGUI", "RECORD", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_Button_4.setText(QtGui.QApplication.translate("SynergiesGUI", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("SynergiesGUI", "CONNECT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SynergiesGUI", "DATE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SynergiesGUI", "File Output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SynergiesGUI", "Last Action ", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("SynergiesGUI", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLicense.setText(QtGui.QApplication.translate("SynergiesGUI", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContact.setText(QtGui.QApplication.translate("SynergiesGUI", "Contact", None, QtGui.QApplication.UnicodeUTF8))

